export const people = [
  {
    name: "Rahul",
    age: 30,
    city: "Pune",
    isEmployed: true,
    vechicle: { hasVehicle: true, type: "car" },
    occupation: "Software Engineer",
    majorIn: "computer science",
    minorIn: "",
    hobbies: [
      { name: "chess", specific: "" },
      { name: "gardening", specific: "when he's not busy coding" },
    ],
    pets: [
      {
        name: "Max",
        type: "Dog",
        breed: "golden retriever",
        age: 4,
        vaccinated: true,
        lovesTo: ["playing fetch in park"],
      },
    ],
  },
  {
    name: "Ananya",
    age: 30,
    city: "Bangalore",
    isEmployed: false,
    vechicle: { hasVehicle: false, type: "" },
    occupation: "",
    majorIn: "computer science",
    minorIn: "graphic design",
    hobbies: [
      { name: "cooking", specific: "often experiments with Italian recipes" },
    ],
    pets: [
      {
        name: "Kiwi",
        type: "parrot",
        breed: "",
        age: 3,
        vaccinated: true,
        lovesTo: ["mimics her voice"],
      },
    ],
  },
  {
    name: "Ramesh",
    age: 45,
    city: "Jaipur",
    isEmployed: true,
    vechicle: { hasVehicle: false, type: "" },
    occupation: "Business man",
    majorIn: "",
    minorIn: "",
    hobbies: [
      { name: "gardening", specific: "rose garden" },
      { name: "reading", specific: "historical fiction" },
    ],
    pets: [
      {
        name: "Bella",
        type: "Cat",
        breed: "Persian",
        age: 3,
        vaccinated: true,
        lovesTo: ["lounging in the sun"],
      },
      {
        name: "Leo",
        type: "Cat",
        breed: "Persian",
        age: 3,
        vaccinated: true,
        lovesTo: ["lounging in the sun"],
      },
    ],
  },
  {
    name: "Kavya",
    age: 28,
    city: "Chennai",
    isEmployed: false,
    vechicle: { hasVehicle: false, type: "" },
    occupation: "professional dancer",
    majorIn: "",
    minorIn: "",
    hobbies: [
      { name: "binge-watching", specific: "sci-fi shows" },
      { name: "reading", specific: "modern fantasy novels" },
    ],
    pets: [
      {
        name: "Snowy",
        type: "rabbit",
        breed: "",
        age: 2,
        vaccinated: true,
        lovesTo: ["enjoys hopping around her backyard", "nibbling on carrots"],
      },
    ],
  },
];
